language: python
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
      #- boost-latest/ppa
      #- george-edison55/precise-backports #cmake-3.x
      #- kubuntu-backports # cmake 2.8.12
    packages:
      - cmake
      ## 


python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n dev python=$TRAVIS_PYTHON_VERSION numpy nose boost hdf5
  - source activate dev
  - conda install -c rdonnelly gcc-6=6.1.0 -v
  - conda install -c conda-forge glpk
  # for a python 2.7 we need concurrent futures
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install futures;
    fi
  #- python setup.py install

script:
  #- chmod +x /home/travis/miniconda/envs/dev/bin/sh
  #- chmod +x /home/travis/miniconda/envs/dev/bin/nosetests
  # Your test script goes here
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate dev
  - export ENV_ROOT="$HOME/miniconda/envs/dev"
  - export ENV_INCLUDE="$ENV_ROOT/include"
  - export ENV_BIN="$ENV_ROOT/bin"
  # 
  # configure cmake
  - cmake -DWITHIN_TRAVIS=ON 
          -DWITH_QPBO=ON
          -DWITH_HDF5=ON
          -DWITH_QPBO=ON
          -DWITH_GLPK=ON 
          -DWITH_CPLEX=OFF 
          -DWITH_GUROBI=OFF
          -DBUILD_CPP_TEST=OFF 
          -DBUILD_PYTHON_TEST=ON 
          -DBUILD_NIFTY_PYTHON=ON 
          -DNOSETESTS_PATH=$ENV_BIN 
          -DBoost_INCLUDE_DIR=$ENV_INCLUDE 
          -DCMAKE_CXX_COMPILER=$ENV_BIN/g++ 
          -DPYTHON_EXECUTABLE=$ENV_BIN/python$TRAVIS_PYTHON_VERSION
          -DPYTHON_MODULE_INSTALL_DIR=/home/travis/miniconda/envs/dev/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
  #
  # build everything
  - make -j 2
  # call the tests
  - make python-test
  # install the probject
  - sudo make install
  - cd src/python/test
  # this is a fucked up way of running python test
  # pls, if someone could fix this =)
  - nosetests  cgp/*.py
  - nosetests  graph/lifted_multicut/*.py
  - nosetests  graph/multicut/*.py
  - nosetests  graph/mincut/*.py
  - nosetests  graph/agglo/*.py
  - nosetests  hdf5/*.py
  - nosetests  tools/*.py