language: cpp
dist: trusty
sudo: required
cache:
  directories:
  - $HOME/.cache/pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
      #- boost-latest/ppa
      #- george-edison55/precise-backports #cmake-3.x
      #- kubuntu-backports # cmake 2.8.12
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-6
      - g++-6
      - g++-multilib
      - python-nose
      - python3-nose
      - python3.5
      - python3.5-dev
      - python3.5-venv
      - libhdf5-serial-dev
      - libboost-all-dev
      - libglpk-dev
      - cmake
      - libboost-test-dev 
      ## 
#before_script:
#  - wget https://github.com/wjakob/pybind11/archive/master.zip
#  - unzip master.zip -d .
#  #
matrix:
  include:
    - os: linux
      compiler: gcc
      script:


        # Link gcc-6 and g++-6 to their standard commands
        - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
        # Export CC and CXX to tell cmake which compiler to use
        - export CC=/usr/bin/gcc-6
        - export CXX=/usr/bin/g++-6
        # Check versions of gcc, g++ and cmake
        - gcc -v && g++ -v && cmake --version


        - pyvenv-3.5 venv
        - pip install numpy
        - pip install nose
        - cmake -DWITHIN_TRAVIS=ON -DBUILD_CPP_TEST=ON -DWITH_GLPK=ON -DWITH_HDF5=ON -DBUILD_NIFTY_PYTHON=ON -DPYBIND11_PYTHON_VERSION=3.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.5m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.5m.so -DPYTHON_EXECUTABLE:FILEPATH=`pwd`/venv/bin/python3.5 
        #- cmake -DWITHIN_TRAVIS=ON -DBUILD_CPP_TEST=ON -DWITH_GLPK=ON -DWITH_HDF5=ON -DBUILD_NIFTY_PYTHON=ON -DPYBIND_ELEVEN_INCLUDE_DIR=pybind11-master/include -DCMAKE_CXX_COMPILER=g++-4.8 -DPYBIND11_PYTHON_VERSION=3.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.5m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.5m.so -DPYTHON_EXECUTABLE:FILEPATH=`pwd`/venv/bin/python3.5 
        - make -j2
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test
        
        - source venv/bin/activate
        - pip install numpy
        - pip install nose
        #- make python-test
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test
        # 
  
    - os: linux
      compiler: gcc
      script:
        - cmake -DWITHIN_TRAVIS=ON -DBUILD_CPP_TEST=ON -DWITH_GLPK=ON -DWITH_HDF5=ON -DBUILD_NIFTY_PYTHON=ON -DPYTHON_EXECUTABLE:/usr/bin/python2.7 
        - make -j2
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test
        
        - pip install numpy
        #- make python-test
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test




    - os: linux
      compiler: gcc-4.8
      script:
        - pyvenv-3.5 venv
        - pip install numpy
        - cmake -DWITHIN_TRAVIS=ON -DBUILD_CPP_TEST=ON -DWITH_GLPK=ON -DWITH_HDF5=ON -DBUILD_NIFTY_PYTHON=ON -DCMAKE_CXX_COMPILER=g++-4.8 -DPYBIND11_PYTHON_VERSION=3.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.5m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.5m.so -DPYTHON_EXECUTABLE:FILEPATH=`pwd`/venv/bin/python3.5 
        #- cmake -DWITHIN_TRAVIS=ON -DBUILD_CPP_TEST=ON -DWITH_GLPK=ON -DWITH_HDF5=ON -DBUILD_NIFTY_PYTHON=ON -DPYBIND_ELEVEN_INCLUDE_DIR=pybind11-master/include -DCMAKE_CXX_COMPILER=g++-4.8 -DPYBIND11_PYTHON_VERSION=3.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.5m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.5m.so -DPYTHON_EXECUTABLE:FILEPATH=`pwd`/venv/bin/python3.5 
        - make -j2
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test
        
        - source venv/bin/activate
        - pip install numpy
        #- make python-test
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test


    - os: osx
      compiler: clang
      script:

        - cmake -DWITHIN_TRAVIS=ON -DBUILD_CPP_TEST=ON -DWITH_GLPK=OFF -DBUILD_NIFTY_PYTHON=ON -DPYBIND_ELEVEN_INCLUDE_DIR=pybind11-master/include -DPYBIND11_PYTHON_VERSION=2.7
        - make -j 2
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test
        - make python-test