language: python
dist: trusty
sudo: required
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n dev python=$TRAVIS_PYTHON_VERSION numpy nose
  - source activate dev

  #- python setup.py install

script:
  # Your test script goes here
  - export ENV_ROOT="$HOME/miniconda/envs/dev3"
  - export ENV_INCLUDE="$ENV_ROOT/include"
  - export ENV_BIN="$ENV_ROOT/bin"
  - cmake -DWITHIN_TRAVIS=ON -DBUILD_CPP_TEST=OFF -DBUILD_PYTHON_TEST=OFF -DWITH_GLPK=OFF -DWITH_HDF5=OFF -DBUILD_NIFTY_PYTHON=ON -DNOSETEST_PATH=$ENV_BIN -DBoost_INCLUDE_DIR=$ENV_INCLUDE
  - make -j 2
  - sudo make install
  - make python-test