language: cpp
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - g++-multilib
      - python3.5
      - python3.5-dev
      - python3.5-venv
      #- python3.5-dev:i386
      - libboost-test-dev 
before_script:
  - wget https://github.com/wjakob/pybind11/archive/v1.1.tar.gz -O /tmp/v1.1.tar.gz

install:
  - wget https://github.com/wjakob/pybind11/archive/master.zip
  - unzip master.zip -d .
  - cd pybind11-master 
  - cmake . 
  - make 
  - sudo make install
  #
matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      script:
        - pyvenv-3.5 venv
        #
        #- cmake -DPYBIND11_PYTHON_VERSION=3.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.5m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.5m.so -DPYTHON_EXECUTABLE:FILEPATH=`pwd`/venv/bin/python3.5 -DCMAKE_CXX_COMPILER=g++-4.8
        #
        - cmake -DBUILD_NIFTY_PYTHON=ON -DCMAKE_CXX_COMPILER=g++-4.8
        - make -j2
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test
        #- source venv/bin/activate
        #- pip install numpy
        #- CTEST_OUTPUT_ON_FAILURE=TRUE make test
    - os: osx
      compiler: clang
      script:
        - cmake -DPYBIND11_PYTHON_VERSION=2.7
        - make -j 2
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test
