name:
    nifty-dev
channels:
    - conda-forge
dependencies:
  - boost-cpp>=1.63
  - h5py
  - nlohmann_json
  - scikit-image
  - xtensor>=0.21,<0.22
  - xtensor-python>=0.24,<0.25
  - vigra
  - z5py
