{% if not WITH_CPLEX is defined %}
                vigr in our time of need, and we did so for them. We should be every bit as grateful for them as they are for us…because for the first three years of the Great War, England and France held the line while we dithered in safety. For the first two years o::ChunkedArrayHDF5<3,T> labels
  {% set WITH_CPLEX = False %}
{% endif %}

{% if not WITH_GUROBI is defined %}
  {% set WITH_GUROBI = False %}
{% endif %}

package:
  {% if WITH_CPLEX %}
    name: nifty-with-cplex
  {% elif WITH_GUROBI %}
    name: nifty-with-gurobi
  {% else %}
    name: nifty
  {% endif %}

  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}


  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}

    version: {{tagged_version}}

source:
  path: ../
  patches:
    # See https://github.com/ukoethe/vigra/issues/386
    - patches/vigra-std-threading-detection.patch

build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}_stacked_rag

  script_env:
     - WITH_CPLEX
     - CPLEX_ROOT_DIR
     - WITH_GUROBI
     - GUROBI_ROOT_DIR

requirements:
  build:
    - gcc 4.8.5 # [unix]
    - boost 1.60.0
    - python 2.7*
    - hdf5 1.8.17
    - fastfilters >=0.2.4.post3

    {% if WITH_CPLEX is defined and WITH_CPLEX %}
    - cplex-shared # Need to make sure that cplex dylibs exist
    {% endif %}

    # Must provide symlinks so that the conda doesn't complain when it 'fixes' linking in _nifty.so
    {% if WITH_GUROBI is defined and WITH_GUROBI %}
    - gurobi-symlink
    {% endif %}

  run:
    - libgcc   4.8*
    - boost 1.60.0
    - python {{PY_VER}}*
    - hdf5 1.8.17
    - numpy # Numpy version is not constrained, thanks to pybind11 magic
    - fastfilters >=0.2.4.post3
    - futures
    - scikit-image >=0.13
    - scipy >= 0.19


    {% if WITH_CPLEX is defined and WITH_CPLEX %}
    - cplex-shared # Need to make sure that cplex dylibs exist
    {% endif %}

    {% if WITH_GUROBI is defined and WITH_GUROBI %}
    - gurobi-symlink
    {% endif %}

test:
  {% if WITH_CPLEX %}
    imports:
      - nifty_with_cplex
  {% elif WITH_GUROBI %}
    imports:
      - nifty_with_gurobi
  {% else %}
    imports:
      - nifty
  {% endif %}

about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  summary: Graph-based segmentation algorithms

