name: C++ and python bindings CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: configure
      run: ./github/workflows/configure.sh
    - name: make
      run: make install
    - name: test
      run: ./github/workflows/test.sh
