name: nifty-build-env
channels:
  - conda-forge
dependencies:
  - boost-cpp>=1.63
  - cmake
  - compilers
  - h5py
  - nlohmann_json
  - scikit-image
  - xtensor>=0.21,<0.22
  - xtensor-python>=0.24,<0.25
  - vigra 1.11.1=*_1025
  - z5py
